### ISSUE TITLE
Detailed Documentation

### ISSUE THREAD

**Issue by 99Jannis** [PatrickLutz11/SoftwareEngineeringProject#13]
Create documentation to guide users through your applications setup, features, and usage. Please provide a meaningful runtime view diagram showing what your application does. The documentation shall be a part of the repository.

**Comment by 99Jannis** [comment]
all functions are documented. But I don't know how much more is necessary. I will look into it today. Maybe there is more info in the provided documents.

**Comment by Master-D1990** [comment]
Good point!
But I don't know yet either.

I think we could improve the README.md - but I'm quite a virgin in this topic.
