### ISSUE TITLE
Shape detection with camera

### ISSUE THREAD

**Issue by 99Jannis** [PatrickLutz11/SoftwareEngineeringProject#26]
if I currently use the Gui with shape detection it outputs this image: 
![image](https://github.com/user-attachments/assets/588fa41f-7dd9-4f5b-8dc3-a0b845e06314)
I will try to further look into the source of the problem, but would be glad with some help

**Comment by 99Jannis** [comment]
problem is probably with shape detection. I encounter the problem with test_image_03.jpg
![image](https://github.com/user-attachments/assets/8204994e-f5d4-4996-a76d-ed54d7524b2c)

**Comment by 99Jannis** [comment]
result.JPG as well and I think I also found the probable error source. further info in the next comment.

Input result.jpg:
![image](https://github.com/user-attachments/assets/10af0234-55fc-4c96-84fd-84267a995be6)
Output result.jpg: 
![image](https://github.com/user-attachments/assets/6b156aa2-c035-4dba-8287-fc98aae746b3)

**Comment by 99Jannis** [comment]
The shape detection looks for ALL contours of an image and if the blur matrix isn't big enough it detects MORE contours. 

So there are probably hundreds of contours it detects and then also wants to detect their color and write it on the image.

**Comment by 99Jannis** [comment]
#possible solution
a relative blur in regards to the size of the image instead of an absolute one, could maybe fix the problem but I'm not sure...

**Comment by Master-D1990** [comment]
We could probably implement some kind of thresholds which are dynamic, reduced until we get a set amount of detected shapes. The downside of it is that it'll almost any time give us the wrong amount of shapes.

Another feature could be a slider in the GUI with the function to set the thresholds manually.

Thus, I'm not sure how important this is for the grading, but we could definitely put some work in it.

**Comment by 99Jannis** [comment]
> ### possible solution
> 
> a relative blur in regards to the size of the image instead of an absolute one, could maybe fix the problem but I'm not sure...

I tried this and it didn't work. but what improved a bit was the recognition if I changed the blur from gaussian to the non-weighted one

**Comment by 99Jannis** [comment]
solved with merge #31 Bugfix shape detection simplified
